# Generated by Django 3.1.1 on 2024-03-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='sessionFirst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='sessionSecond',
            field=models.FloatField(default=0),
        ),
    ]
